
services:

  db:
    image: mysql:8.4
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./backend/init/sql:/docker-entrypoint-initdb.d
      - mysqlData:/var/lib/mysql

  api:
    build: ./backend
    container_name: express_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    command: ["/app/wait-for-db.sh", "npm", "start"]

  frontend: 
    build: ./frontend
    container_name: our-shelves
    ports:
      - '5173:5173'
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:3000
    
  
volumes:
  mysqlData: