FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN apt-get update && apt-get install -y netcat-openbsd

COPY . .

RUN chmod +x wait-for-db.sh

EXPOSE 3000

CMD ["npm", "start"]